#!/usr/bin/env python3
"""
Generate a .http REST Client file from @mcp.tool() functions in src/server.py.

Static AST parse — does NOT need the server to be running. Emits one request
block per tool plus a `tools/list` discovery request. The endpoint URL is a
placeholder you swap in when the server is switched to Streamable HTTP.

Usage:
    python tools/generate_rest_file.py
    python tools/generate_rest_file.py --server src/server.py --out api.http
    python tools/generate_rest_file.py --url http://localhost:8000/mcp
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path
from typing import Any


_NO_DEFAULT = object()


def is_mcp_tool_decorator(dec: ast.expr) -> bool:
    """Match @mcp.tool() and @mcp.tool."""
    if isinstance(dec, ast.Call):
        dec = dec.func
    return (
        isinstance(dec, ast.Attribute)
        and isinstance(dec.value, ast.Name)
        and dec.value.id == "mcp"
        and dec.attr == "tool"
    )


def ann_name(ann: ast.expr | None) -> str:
    if ann is None:
        return "any"
    if isinstance(ann, ast.Name):
        return ann.id
    if isinstance(ann, ast.Attribute):
        return ann.attr
    if isinstance(ann, ast.Subscript):
        outer = ann_name(ann.value)
        inner = (
            "any" if isinstance(ann.slice, ast.Tuple) else ann_name(ann.slice)
        )
        return f"{outer}[{inner}]"
    return "any"


def unwrap_optional(ann: ast.expr) -> tuple[ast.expr | None, bool]:
    """Optional[X] / Union[X, None] -> (X, True); else (ann, False)."""
    if not isinstance(ann, ast.Subscript):
        return ann, False
    outer = ann.value
    outer_name = outer.id if isinstance(outer, ast.Name) else (
        outer.attr if isinstance(outer, ast.Attribute) else None
    )
    if outer_name == "Optional":
        return ann.slice, True
    if outer_name == "Union" and isinstance(ann.slice, ast.Tuple):
        non_none = [
            e for e in ann.slice.elts
            if not (isinstance(e, ast.Constant) and e.value is None)
        ]
        if len(non_none) == 1 and len(non_none) < len(ann.slice.elts):
            return non_none[0], True
    return ann, False


SAMPLES: dict[str, Any] = {
    "str": "<string>",
    "int": 0,
    "float": 0.0,
    "bool": False,
    "list": [],
    "List": [],
    "dict": {},
    "Dict": {},
    "any": "<value>",
    "Any": "<value>",
}


def sample_for(ann: ast.expr | None, default: Any) -> Any:
    """Default value wins; otherwise infer a placeholder from the annotation."""
    if default is not _NO_DEFAULT:
        return default
    if ann is None:
        return "<value>"
    inner, optional = unwrap_optional(ann)
    if optional:
        return None
    base = ann_name(inner).split("[", 1)[0]
    return SAMPLES.get(base, "<value>")


def literal_default(node: ast.expr) -> Any:
    try:
        return ast.literal_eval(node)
    except Exception:
        return _NO_DEFAULT


def parse_tools(src_path: Path) -> list[dict]:
    tree = ast.parse(src_path.read_text(), filename=str(src_path))
    tools: list[dict] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not any(is_mcp_tool_decorator(d) for d in node.decorator_list):
            continue

        args = node.args.args
        defaults = node.args.defaults
        pad = [_NO_DEFAULT] * (len(args) - len(defaults))
        full_defaults = pad + [literal_default(d) for d in defaults]

        params, sample_args = [], {}
        for arg, default in zip(args, full_defaults):
            params.append({
                "name": arg.arg,
                "type": ann_name(arg.annotation),
                "required": default is _NO_DEFAULT,
                "default": None if default is _NO_DEFAULT else default,
            })
            sample_args[arg.arg] = sample_for(arg.annotation, default)

        tools.append({
            "name": node.name,
            "description": (ast.get_docstring(node) or "").strip(),
            "params": params,
            "sample_args": sample_args,
        })
    return tools


def render(tools: list[dict], url: str, source: Path) -> str:
    out: list[str] = [
        f"# Auto-generated by {Path(__file__).name} from {source}",
        "# MCP JSON-RPC over Streamable HTTP. Adjust @url if the server endpoint differs.",
        "",
        f"@url = {url}",
        "",
    ]
    for i, t in enumerate(tools, start=1):
        first_line = t["description"].splitlines()[0] if t["description"] else ""
        header = f"### {t['name']}"
        if first_line:
            header += f" — {first_line}"
        out.append(header)
        for p in t["params"]:
            tag = "required" if p["required"] else f"default={p['default']!r}"
            out.append(f"# {p['name']}: {p['type']} ({tag})")
        body = {
            "jsonrpc": "2.0",
            "id": i,
            "method": "tools/call",
            "params": {"name": t["name"], "arguments": t["sample_args"]},
        }
        out += [
            "POST {{url}}",
            "Content-Type: application/json",
            "Accept: application/json, text/event-stream",
            "",
            json.dumps(body, indent=2),
            "",
        ]
    out += [
        "### tools/list — discover available tools",
        "POST {{url}}",
        "Content-Type: application/json",
        "Accept: application/json, text/event-stream",
        "",
        json.dumps({"jsonrpc": "2.0", "id": 0, "method": "tools/list"}, indent=2),
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--server", type=Path, default=Path("src/server.py"))
    ap.add_argument("--out", type=Path, default=Path("api.http"))
    ap.add_argument("--url", default="http://localhost:8000/mcp")
    args = ap.parse_args()

    if not args.server.exists():
        print(f"error: server file not found: {args.server}", file=sys.stderr)
        return 2

    tools = parse_tools(args.server)
    if not tools:
        print("error: no @mcp.tool() functions found", file=sys.stderr)
        return 1

    args.out.write_text(render(tools, args.url, args.server))
    names = ", ".join(t["name"] for t in tools)
    print(f"wrote {args.out} — {len(tools)} tool(s): {names}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
