"""
seclist_selector.py — LLM-driven SecLists wordlist selection
============================================================

Replaces the static ``data/cwe_wordlist_map.json`` lookup that previously
decided which SecLists wordlist to fuzz with. Instead of a hand-maintained
CWE→wordlist table, this module hands the language model three things:

  1. the **API** under test (endpoint, HTTP method, target URL),
  2. the **API's source code** (the vulnerable function), and
  3. a **catalog of the wordlist files available in the SecLists repo**
     (``data/seclists_catalog.txt``, regenerated by
     ``tools/build_seclists_catalog.py``).

The model then "checks the SecLists repo" — i.e. picks, from the catalog, the
wordlist(s) best suited to fuzzing this specific vulnerability — and returns
their paths. Every returned path is validated against the catalog, so the
model cannot invent a path that does not exist.

Public API:
    select_wordlists(finding, function_source, api_info, ...) -> (paths, source)

``source`` is one of:
    "model"    — the LLM picked valid wordlist paths
    "fallback" — the LLM failed/returned nothing valid; the static
                 cwe_wordlist_map.json was used instead

Paths are relative to the SecLists root, exactly as ffuf consumes them
(``/SecLists/<path>`` inside the Docker image).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

import requests

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CATALOG_PATH = PROJECT_ROOT / "data" / "seclists_catalog.txt"
_MAP_PATH = PROJECT_ROOT / "data" / "cwe_wordlist_map.json"

DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_MODEL = "qwen3"

# Fallback map — used only when the model is unreachable or returns no valid
# catalog path. Keeps the pipeline producing a runnable fuzz.sh either way.
with _MAP_PATH.open() as _f:
    CWE_WORDLIST_MAP: dict = json.load(_f)


SELECTOR_SYSTEM_PROMPT = (
    "You are a security fuzzing assistant. You are given an HTTP API endpoint, "
    "its source code, and a confirmed vulnerability finding for that code. You "
    "are also given a catalog of wordlist files that exist in the SecLists "
    "repository. Choose the wordlist(s) from the catalog that are best suited "
    "to fuzz-testing this specific vulnerability and code context — for example "
    "SQL injection lists for CWE-89, XSS lists for CWE-79, path-traversal/LFI "
    "lists for CWE-22, command-injection lists for CWE-78. "
    "Return ONLY a JSON array of catalog paths, copied EXACTLY as they appear in "
    "the catalog, most relevant first. Do not invent paths that are not in the "
    "catalog. Do not include any commentary or markdown."
)


def load_catalog(path: Path = DEFAULT_CATALOG_PATH) -> list[str]:
    """Read the SecLists catalog (one wordlist path per line)."""
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    ]


def build_user_prompt(
    api_info: dict,
    function_source: str,
    finding: dict,
    catalog: list[str],
) -> str:
    """Format the user message: the (API, source) pair, the finding, the catalog."""
    api_block = {
        "endpoint":   api_info.get("endpoint", ""),
        "method":     api_info.get("method", ""),
        "target_url": api_info.get("target_url", ""),
        "function":   api_info.get("function", ""),
    }
    finding_block = {
        "cwe_id":      finding.get("cwe_id", ""),
        "cwe_name":    finding.get("cwe_name", ""),
        "severity":    finding.get("severity", ""),
        "evidence":    finding.get("evidence", ""),
        "description": finding.get("description", ""),
    }
    return (
        f"API under test:\n{json.dumps(api_block, indent=2)}\n\n"
        f"API source code:\n```python\n{function_source.strip()}\n```\n\n"
        f"Vulnerability finding:\n{json.dumps(finding_block, indent=2)}\n\n"
        f"Available SecLists wordlists (choose from these only):\n"
        + "\n".join(catalog)
        + "\n\nReturn ONLY a JSON array of the chosen wordlist paths."
    )


def _extract_json_array_of_strings(text: str) -> list[str]:
    """Tolerant extraction of a JSON string array from model output."""
    text = text.strip()
    # Drop any reasoning block emitted by thinking models (e.g. Qwen 3).
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\s*```$", "", text, flags=re.MULTILINE)
    text = text.strip()

    candidates = []
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            candidates.append(parsed)
    except json.JSONDecodeError:
        pass

    if not candidates:
        m = re.search(r"\[.*\]", text, re.DOTALL)
        if m:
            try:
                parsed = json.loads(m.group())
                if isinstance(parsed, list):
                    candidates.append(parsed)
            except json.JSONDecodeError:
                pass

    for arr in candidates:
        out = [str(x).strip() for x in arr if isinstance(x, str) and str(x).strip()]
        if out:
            return out
    return []


class SecListClient:
    """Thin, fail-soft Ollama /api/chat client for wordlist selection.

    Unlike vuln_scanner.OllamaClient this never exits the process — on any
    network error it raises requests.RequestException so the caller can fall
    back to the static map.
    """

    def __init__(
        self,
        base_url: str = DEFAULT_OLLAMA_URL,
        model: str = DEFAULT_MODEL,
        temperature: float = 0.2,
        num_predict: int = 512,
    ):
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.temperature = temperature
        self.num_predict = num_predict

    def chat(self, system: str, user: str, timeout: int = 120) -> str:
        # Reasoning models (e.g. Qwen 3) emit <think>…</think> by default, which
        # bloats output and breaks JSON parsing. Disable it via think=False, and
        # retry without the flag if the model/Ollama version rejects it.
        options = {
            "temperature": self.temperature,
            "num_predict": self.num_predict,
            "top_p": 0.9,
        }
        for use_think_flag in (True, False):
            payload = {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "stream": False,
                "options": options,
            }
            if use_think_flag:
                payload["think"] = False
            r = requests.post(f"{self.base_url}/api/chat", json=payload, timeout=timeout)
            if r.status_code == 400 and use_think_flag:
                continue  # model doesn't support the think flag — retry without it
            r.raise_for_status()
            return r.json().get("message", {}).get("content", "")
        return ""


def _fallback_paths(cwe_id: str) -> list[str]:
    """SecLists-relative wordlist paths from the static map — used when the LLM fails."""
    return CWE_WORDLIST_MAP.get(cwe_id) or CWE_WORDLIST_MAP.get("_default", [])


def select_wordlists(
    finding: dict,
    function_source: str,
    api_info: dict,
    catalog: Optional[list[str]] = None,
    model: str = DEFAULT_MODEL,
    base_url: str = DEFAULT_OLLAMA_URL,
    max_wordlists: int = 2,
    client: Optional[SecListClient] = None,
) -> tuple[list[str], str]:
    """
    Ask the LLM which SecLists wordlist(s) to fuzz with for one finding.

    Returns (paths, source). ``paths`` are catalog-relative SecLists paths.
    ``source`` is "model" if the LLM produced valid catalog paths, else
    "fallback" (static cwe_wordlist_map.json).
    """
    catalog = catalog if catalog is not None else load_catalog()
    catalog_set = set(catalog)
    cwe_id = finding.get("cwe_id", "")

    if catalog:
        cli = client or SecListClient(base_url=base_url, model=model)
        user_prompt = build_user_prompt(api_info, function_source, finding, catalog)
        try:
            raw = cli.chat(SELECTOR_SYSTEM_PROMPT, user_prompt)
            picked = _extract_json_array_of_strings(raw)
            # Keep only real catalog paths, preserve model order, dedupe.
            seen: set[str] = set()
            valid: list[str] = []
            for p in picked:
                if p in catalog_set and p not in seen:
                    seen.add(p)
                    valid.append(p)
            if valid:
                return valid[:max_wordlists], "model"
        except requests.RequestException:
            pass

    return _fallback_paths(cwe_id)[:max_wordlists], "fallback"
